# Generated by Django 5.1.1 on 2024-11-03 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='icon',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='nested_lesaon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nested_lessons', to='courses.course'),
        ),
    ]
