# Generated by Django 5.1.1 on 2024-11-03 07:19

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_course_alter_lesson_nested_lesaon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestDB',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
